version: "3.9"

services:
  ros-demo:
    build: 
      context: ./..
      dockerfile: ./docker/Dockerfile
    container_name: ros-demo
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,utility,display"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - type: bind
        source: ./../demo_package
        target: /app/ros_ws/src/demo_package
    ports:
      - "8888:8888"
    # command: roslaunch panther_gazebo panther_rviz.launch