version: "3.9"

services:
  ros-demo:
    build: 
      context: ./..
      dockerfile: ./docker/Dockerfile
    container_name: ros-demo
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,utility,display"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - type: bind
        source: ./../ros_ws
        target: /app/demo_ros_ws/src
    command: roslaunch demo_package demo_bringup.launch